### ISSUE TITLE
Switch to a StockChart with working zoom and range selection

### ISSUE THREAD

**Issue by pcorey** [benstr/moneybot#26]

**Comment by sircharleswatson** [comment]
@pcorey We are using a stock chart, we just need to get the zoom and range stuff working

**Comment by pcorey** [comment]
@sircharleswatson Word. I meant a "StockChart" style chart within High/StockChart. I have everything mostly working in [my fork](https://github.com/pcorey/moneybot) including the date range buttons (which replace the dropdown). I'm just working on fixing a few kinks, like the legend no longer appearing.
