### ISSUE TITLE
Is moneybot ready for real trading?

### ISSUE THREAD

**Issue by ansarizafar** [benstr/moneybot#27]
I am a Meteor developer and I am also interested in Forex trading. I would like to know is moneybot  ready for real trading with real money. I have used https://www.dukascopy.com/ in the past for automatic trading but I was not able to make my Forex bot profitable.

**Comment by benstr** [comment]
It is being used now for live trading but it is very much a work in progress and lacks the automatic trading features.... actually it is just a currency strength chart right now. I should make a readme which outlines our roadmap :)
