### ISSUE TITLE
make it easier to select a currency pair

### ISSUE THREAD

**Issue by eymiha** [benstr/moneybot#34]
It's tedious to select two currencies by unclicking currency names on the chart.

**Comment by benstr** [comment]
I hear ya on that @eymiha. Any suggestion on how we can make it easier?

**Comment by eymiha** [comment]
Funny you should ask ;-)  I have a pull request coming... it depends on the fix I did for issue20, though.

**Comment by benstr** [comment]
cool! There it is :) #35
